"""
src/sot_graph/analytics/bundle.py
Deterministic Fact Bundler for sot-graph.
Extracts structured codebase facts from sot.db into high-density Markdown artifacts
serving as Stage 1 inputs for LLM-assisted architectural report synthesis.
"""
from __future__ import annotations
import json
import os
from pathlib import Path
import re
from typing import Any, Callable, Dict, List, Optional

from sot_graph.analytics.architecture import (
    ArchitecturalLayer,
    ArchitectureProfile,
    FunctionalModule,
    classify_node_layer,
    is_test_or_mock_path,
)
from sot_graph.analytics.diagnostics import AnalysisResult, analyze_graph
from sot_graph.analytics.graph import AnalyticsGraph
from sot_graph.db import Database

# Conformance status vocabulary, emitted identically in
# 04_dependencies_violations.md and 05_system_metrics.json. The bundler never
# reads a declared layer-policy artifact, so strict conformance is never claimed.
CONFORMANCE_NOT_ASSESSED = "NOT_ASSESSED"
CONFORMANCE_NO_DETECTED_VIOLATIONS = "NO_DETECTED_VIOLATIONS"
CONFORMANCE_VIOLATIONS_DETECTED = "VIOLATIONS_DETECTED"

_DETECTOR_CLASSIFICATION = "AST_PATH_HEURISTIC"
_DETECTOR_SUPPORTED_RULES = ["LAYER_BYPASS", "INVERTED_DEPENDENCY"]
_DETECTOR_LIMITATIONS = [
    "Layer policy is not observable: no declared architecture-rules artifact is ingested; "
    "layer roles are inferred from path/label/keyword heuristics.",
    "Only LAYER_BYPASS (Presentation->Data) and INVERTED_DEPENDENCY (Data/Domain->Presentation) "
    "rules are supported; all other constraint types are out of scope.",
    "Edges with any UNKNOWN-layer endpoint are not assessed; assessed_edge_fraction publishes "
    "the denominator. Absence of findings is NOT evidence of conformance.",
]

class ArchitectureBundler:
    """Extracts and writes structured architectural fact bundles from AnalyticsGraph."""

    def __init__(
        self,
        db: Optional[Database] = None,
        root_dir: str = ".",
        graph: Optional[AnalyticsGraph] = None,
        include_tests: bool = False,
        cancel_check: Optional[Callable[[], bool]] = None,
    ):
        self.root_dir = os.path.abspath(root_dir)
        self.include_tests = include_tests
        if graph is not None:
            self.graph = graph
        elif db is not None:
            self.graph = AnalyticsGraph.from_database(db)
        else:
            raise ValueError("Either db or graph must be provided to ArchitectureBundler")
        self.analysis: AnalysisResult = analyze_graph(self.graph, cancel_check=cancel_check)
        self.profile: Optional[ArchitectureProfile] = self.analysis.architecture_profile

    def extract_bundle(self, output_dir: Optional[str] = None) -> Dict[str, str]:
        """
        Generate all 5 fact bundle artifacts and return a dictionary of {filename: content}.
        If output_dir is provided, writes files directly to disk.
        """
        if output_dir is None:
            output_dir = os.path.join(self.root_dir, ".sot", "bundle")

        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)

        bundle = {
            "01_module_inventory.md": self._generate_module_inventory(),
            "02_routing_endpoints.md": self._generate_routing_endpoints(),
            "03_workflows_states.md": self._generate_workflows_and_states(),
            "04_dependencies_violations.md": self._generate_dependencies_and_violations(),
            "05_system_metrics.json": self._generate_system_metrics_json(),
        }

        for filename, content in bundle.items():
            file_path = out_path / filename
            file_path.write_text(content, encoding="utf-8")

        return bundle

    def _generate_module_inventory(self) -> str:
        """Generate 01_module_inventory.md listing all functional modules and entities."""
        lines = [
            "# Fact Bundle 01: Functional Module Inventory & Feature Taxonomy",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
            "## 1. Overview of Bounded Functional Modules",
            "",
        ]

        if not self.profile or not self.profile.functional_modules:
            lines.append("*(No structured functional modules discovered)*\n")
            return "\n".join(lines)

        mods: List[FunctionalModule] = self.profile.functional_modules
        if not self.include_tests:
            filtered_mods = []
            for mod in mods:
                files = [f for f in mod.internal_files if not is_test_or_mock_path(f)]
                if not files and (is_test_or_mock_path(mod.name) or "test" in mod.name.lower()):
                    continue
                filtered_symbols = [s for s in mod.sample_symbols if not is_test_or_mock_path(s)]
                filtered_entities = [e for e in mod.core_entities if not is_test_or_mock_path(e)]
                filtered_entrypoints = [ep for ep in mod.entrypoints if not is_test_or_mock_path(ep)]
                filtered_mods.append(
                    FunctionalModule(
                        name=mod.name,
                        category=mod.category,
                        responsibility=mod.responsibility,
                        node_count=mod.node_count if not files else max(len(filtered_symbols), len(files)),
                        file_count=len(files) if files else mod.file_count,
                        core_entities=filtered_entities,
                        entrypoints=filtered_entrypoints,
                        dependencies=mod.dependencies,
                        sample_symbols=filtered_symbols,
                        internal_files=files,
                    )
                )
            mods = filtered_mods

        if not mods:
            lines.append("*(No structured functional modules discovered)*\n")
            return "\n".join(lines)

        lines.extend([
            "| Module Name | Category | Primary Responsibility | Core Entities / Models | Entrypoints / Handlers | Dependencies | Nodes / Files |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :-: |",
        ])

        for mod in mods:
            entities = ", ".join(f"`{e}`" for e in mod.core_entities[:4]) or "*None*"
            if len(mod.core_entities) > 4:
                entities += f" *(+{len(mod.core_entities)-4} more)*"
            entrypoints = ", ".join(f"`{ep}`" for ep in mod.entrypoints[:3]) or "*None*"
            if len(mod.entrypoints) > 3:
                entrypoints += f" *(+{len(mod.entrypoints)-3} more)*"

            deps = ", ".join(f"`{d}`" for d in mod.dependencies[:3]) or "*Standalone*"
            if len(mod.dependencies) > 3:
                deps += f" *(+{len(mod.dependencies)-3} more)*"

            lines.append(
                f"| **{mod.name}** | `{mod.category}` | {mod.responsibility} | {entities} | {entrypoints} | {deps} | {mod.node_count} / {mod.file_count} |"
            )

        lines.extend([
            "",
            "---",
            "",
            "## 2. Deep-Dive Per Module & File Inventory",
            "",
        ])

        for mod in mods:
            lines.append(f"### Module: `{mod.name}` ({mod.category})")
            lines.append(f"- **Primary Responsibility:** {mod.responsibility}")
            lines.append(f"- **Total Nodes:** {mod.node_count} | **Total Files:** {mod.file_count}")
            lines.append(f"- **Dependencies:** {', '.join(f'`{d}`' for d in mod.dependencies) or '*None*'}")
            
            if mod.core_entities:
                lines.append(f"- **Core Entities / Domain Models:** {', '.join(f'`{e}`' for e in mod.core_entities)}")
            if mod.entrypoints:
                lines.append(f"- **Entrypoints / Controllers / Routers:** {', '.join(f'`{ep}`' for ep in mod.entrypoints)}")
            
            if mod.sample_symbols:
                lines.append("- **Key Methods & Symbols:**")
                for sym in mod.sample_symbols[:10]:
                    lines.append(f"  - `{sym}`")

            if mod.internal_files:
                lines.append("- **Internal Source Files:**")
                for f in mod.internal_files[:15]:
                    lines.append(f"  - `{f}`")
                if len(mod.internal_files) > 15:
                    lines.append(f"  - *... and {len(mod.internal_files) - 15} additional files*")
            lines.append("")

        return "\n".join(lines)

    def _generate_routing_endpoints(self) -> str:
        """Generate 02_routing_endpoints.md detailing HTTP API, UI Pages, and Event Routes."""
        lines = [
            "# Fact Bundle 02: Routing Architecture & Endpoint Inventory",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
        ]

        if not self.profile or not self.profile.routing_architecture:
            lines.append("*(No routing architecture discovered)*\n")
            return "\n".join(lines)

        ra = self.profile.routing_architecture
        http_routes = ra.http_routes
        ui_routes = ra.ui_routes
        event_routes = ra.event_routes

        if not self.include_tests:
            http_routes = [r for r in http_routes if not is_test_or_mock_path(r.file_anchor.split(":")[0])]
            ui_routes = [r for r in ui_routes if not is_test_or_mock_path(r.file_anchor.split(":")[0])]
            event_routes = [r for r in event_routes if not is_test_or_mock_path(r.file_anchor.split(":")[0])]

        total_routes = len(http_routes) + len(ui_routes) + len(event_routes)
        lines.append(f"**Total Discovered Routes:** `{total_routes}` ("
                     f"HTTP APIs: `{len(http_routes)}`, "
                     f"UI Pages / Views: `{len(ui_routes)}`, "
                     f"Event / Messaging: `{len(event_routes)}`)\n")

        # 1. HTTP APIs
        lines.extend([
            "## 1. HTTP API Route Endpoints",
            "",
            "| Method | Endpoint / URI Pattern | Controller / Handler Function | Source Anchor (File:Line) | Auth / Guard | Target Layer |",
            "| :---: | :--- | :--- | :--- | :--- | :--- |",
        ])
        if http_routes:
            for r in http_routes:
                method = r.method or "ANY"
                auth = f"`{r.auth_guard}`" if r.auth_guard else "*Public / Default*"
                layer = r.target_layer or "API Layer"
                lines.append(
                    f"| `{method}` | `{r.path_or_pattern}` | `{r.handler}` | `{r.file_anchor}:{r.line}` | {auth} | `{layer}` |"
                )
        else:
            lines.append("| - | *No HTTP API endpoints found* | - | - | - | - |")
        lines.append("")

        # 2. UI Pages
        lines.extend([
            "## 2. UI Page & Navigation Routes",
            "",
            "| Page / Route Pattern | UI Component / View Class | Source Anchor (File:Line) | Target Layer |",
            "| :--- | :--- | :--- | :--- |",
        ])
        if ui_routes:
            for r in ui_routes:
                layer = r.target_layer or "Presentation"
                lines.append(
                    f"| `{r.path_or_pattern}` | `{r.handler}` | `{r.file_anchor}:{r.line}` | `{layer}` |"
                )
        else:
            lines.append("| *No UI page routes found* | - | - | - |")

        # 3. Event Busses & State Dispatches
        lines.extend([
            "## 3. Event Bus & State Dispatches",
            "",
            "| Event / State Pattern | Handler / Emitter Class | Source Anchor (File:Line) |",
            "| :--- | :--- | :--- |",
        ])
        if event_routes:
            for r in event_routes:
                lines.append(
                    f"| `{r.path_or_pattern}` | `{r.handler}` | `{r.file_anchor}:{r.line}` |"
                )
        else:
            lines.append("| *No event dispatches found* | - | - |")

        return "\n".join(lines)

    def _generate_workflows_and_states(self) -> str:
        """Generate 03_workflows_states.md discovering state machines, cron jobs, and background workers."""
        lines = [
            "# Fact Bundle 03: Workflows, State Machines & Background Automation",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
            "## 1. Discovered State Machines & Lifecycle Enums",
            "",
        ]

        state_nodes = []
        cron_nodes = []
        service_nodes = []

        for _node_id, data in self.graph.nodes.items():
            label = str(data.get("label", ""))
            path = str(data.get("path", ""))
            kind = str(data.get("kind", ""))

            if not self.include_tests and is_test_or_mock_path(path):
                continue
            # Detect state machines / status fields
            if re.search(r"(state|status|stage|lifecycle|step|phase)", label, re.I) or \
               re.search(r"(state|status|workflow)", path, re.I):
                state_nodes.append((label, path, kind))

            # Detect cron jobs / scheduled tasks
            if re.search(r"(cron|schedule|periodic|background|worker|interval|reminder)", label, re.I) or \
               re.search(r"(cron|task|job)", path, re.I):
                cron_nodes.append((label, path, kind))

            # Detect external services & connectors (generic signals only; no
            # domain-specific product/gateway name assumptions).
            if re.search(r"(connector|client|integration|api_service|gateway)", label, re.I) or \
               re.search(r"(integration|connector|client)", path, re.I):
                service_nodes.append((label, path, kind))

        if state_nodes:
            lines.extend([
                "| State / Workflow Node | Entity / File Path | Kind |",
                "| :--- | :--- | :--- |",
            ])
            for lbl, p, k in state_nodes[:25]:
                lines.append(f"| `{lbl}` | `{p}` | `{k}` |")
            if len(state_nodes) > 25:
                lines.append(f"| *... and {len(state_nodes)-25} more workflow symbols* | - | - |")
        else:
            lines.append("*(No explicit state machine symbols detected)*")
        lines.append("")

        lines.extend([
            "## 2. Background Workers, Cron Jobs & Scheduled Tasks",
            "",
        ])
        if cron_nodes:
            lines.extend([
                "| Worker / Cron Job Symbol | File Path | Kind |",
                "| :--- | :--- | :--- |",
            ])
            for lbl, p, k in cron_nodes[:25]:
                lines.append(f"| `{lbl}` | `{p}` | `{k}` |")
            if len(cron_nodes) > 25:
                lines.append(f"| *... and {len(cron_nodes)-25} more background tasks* | - | - |")
        else:
            lines.append("*(No explicit background cron workers detected)*")
        lines.append("")

        lines.extend([
            "## 3. Integration Connectors & External Gateway Handlers",
            "",
        ])
        if service_nodes:
            lines.extend([
                "| Connector / Service Symbol | File Path | Kind |",
                "| :--- | :--- | :--- |",
            ])
            for lbl, p, k in service_nodes[:25]:
                lines.append(f"| `{lbl}` | `{p}` | `{k}` |")
            if len(service_nodes) > 25:
                lines.append(f"| *... and {len(service_nodes)-25} more connector symbols* | - | - |")
        else:
            lines.append("*(No explicit external connectors detected)*")
        lines.append("")

        return "\n".join(lines)

    def _compute_detector_coverage(self) -> Dict[str, Any]:
        """Publish denominators matching the detector's eligibility: an edge is
        assessed only when both endpoints exist and classify as non-UNKNOWN layers."""
        node_layers = {
            node_id: classify_node_layer(node_id, data)
            for node_id, data in self.graph.nodes.items()
        }
        total_nodes = len(node_layers)
        classified_nodes = sum(
            1 for layer in node_layers.values() if layer is not ArchitecturalLayer.UNKNOWN
        )

        total_edges = len(self.graph.edges)
        assessed_edges = 0
        for edge in self.graph.edges:
            l_src = node_layers.get(edge["src"], ArchitecturalLayer.UNKNOWN)
            l_dst = node_layers.get(edge["dst"], ArchitecturalLayer.UNKNOWN)
            if l_src is not ArchitecturalLayer.UNKNOWN and l_dst is not ArchitecturalLayer.UNKNOWN:
                assessed_edges += 1

        return {
            "total_nodes": total_nodes,
            "classified_nodes": classified_nodes,
            "classified_node_fraction": round(classified_nodes / total_nodes, 4) if total_nodes else 0.0,
            "total_edges": total_edges,
            "assessed_edges": assessed_edges,
            "assessed_edge_fraction": round(assessed_edges / total_edges, 4) if total_edges else 0.0,
        }

    def _assess_conformance(self) -> Dict[str, Any]:
        """Single source of truth for the conformance verdict, shared by markdown + JSON."""
        violations = self.profile.violations if self.profile else None
        coverage = self._compute_detector_coverage()

        if violations is None:
            # Detector never ran, so no edge counts as assessed.
            coverage["assessed_edges"] = 0
            coverage["assessed_edge_fraction"] = 0.0
            status = CONFORMANCE_NOT_ASSESSED
            summary = "Architecture profile unavailable; the violation detector did not run."
        elif violations:
            status = CONFORMANCE_VIOLATIONS_DETECTED
            summary = (
                f"{len(violations)} candidate finding(s) from heuristic rules; each is anchored "
                "to the observed edge (source/target symbols and paths) and is NOT verified "
                "against any declared layer policy."
            )
        elif coverage["assessed_edges"] == 0:
            status = CONFORMANCE_NOT_ASSESSED
            summary = (
                "No layer policy observable and no edges within the detector's supported scope; "
                "the detector had nothing to assess. Absence of findings is not evidence of conformance."
            )
        else:
            status = CONFORMANCE_NO_DETECTED_VIOLATIONS
            summary = (
                f"Detector ran over {coverage['assessed_edges']} in-scope edge(s) and found no "
                "violations within the supported scope. Strict conformance is NOT claimed: the "
                "layer policy is not observable and classification is heuristic."
            )

        return {
            "status": status,
            "summary": summary,
            "layer_policy_observable": False,
            "strict_conformance_claimed": False,
            "violations_detected": len(violations) if violations else 0,
            "finding_nature": "HEURISTIC_RULE_CANDIDATES",
            "detector": {
                "classification_method": _DETECTOR_CLASSIFICATION,
                "supported_rules": list(_DETECTOR_SUPPORTED_RULES),
                **coverage,
                "limitations": list(_DETECTOR_LIMITATIONS),
            },
        }

    def _render_conformance_markdown(self, conf: Dict[str, Any]) -> List[str]:
        """Render the conformance block for 04_dependencies_violations.md (mirrors the JSON)."""
        d = conf["detector"]
        lines = [
            "## 1. Architectural Conformance Assessment (Scoped Detector Findings)",
            "",
            "> **Evidence policy:** This section reports ONLY what the rule detector observed. "
            "The detector cannot observe the project's declared layer policy (none is ingested); "
            "layer roles are heuristic (`" + d["classification_method"] + "`). Findings are "
            "`" + conf["finding_nature"] + "` (candidate matches, not verified violations). "
            "Absence of findings is NOT evidence of conformance.",
            "",
            f"- **Conformance status:** `{conf['status']}` — {conf['summary']}",
            f"- **Detector coverage:** assessed edges `{d['assessed_edges']}` / `{d['total_edges']}` "
            f"(`{d['assessed_edge_fraction']}`); classified nodes `{d['classified_nodes']}` / "
            f"`{d['total_nodes']}` (`{d['classified_node_fraction']}`)",
            f"- **Supported rules:** {', '.join(f'`{r}`' for r in d['supported_rules'])}",
            "- **Limitations:**",
        ]
        for lim in d["limitations"]:
            lines.append(f"  - {lim}")
        lines.append("")
        return lines

    def _generate_dependencies_and_violations(self) -> str:
        """Generate 04_dependencies_violations.md capturing God nodes, blast radius, and layer violations."""
        conf = self._assess_conformance()
        lines = [
            "# Fact Bundle 04: Inter-Module Dependencies & Architectural Violations",
            "> **Generated by sot-graph Architecture Bundler**",
            "",
        ]
        lines.extend(self._render_conformance_markdown(conf))

        lines.extend([
            "### 1.1 Candidate Rule Findings (heuristic; within supported scope)",
            "",
        ])

        violations = self.profile.violations if self.profile else []
        if violations:
            lines.extend([
                "| Severity | Violation Type | Source Symbol & Path | Target Symbol & Path | Description & Recommendation |",
                "| :---: | :--- | :--- | :--- | :--- |",
            ])
            for v in violations:
                sev = f"**{v.severity}**"
                src = f"`{v.source_node}`<br/>*({v.source_path})*" if v.source_path else f"`{v.source_node}`"
                tgt = f"`{v.target_node}`<br/>*({v.target_path})*" if v.target_path else f"`{v.target_node}`"
                lines.append(
                    f"| {sev} | `{v.violation_type}` | {src} | {tgt} | {v.description}<br/>**Fix:** {v.recommendation} |"
                )
        elif conf["status"] == CONFORMANCE_NO_DETECTED_VIOLATIONS:
            lines.append(
                "No violations detected within the supported scope published above. "
                "This is a scoped absence-of-findings statement, not a conformance guarantee."
            )
        else:
            lines.append(
                "*Not assessed:* no conformance statement can be made — "
                "see status, coverage, and limitations above."
            )
        lines.append("")

        # 2. God Nodes / High Blast Radius
        lines.extend([
            "## 2. High Blast-Radius Entities (God Nodes)",
            "",
            "| Entity / Symbol | In-Degree (Incoming Calls) | Out-Degree (Outgoing Calls) | Total Degree | Blast Radius Risk |",
            "| :--- | :---: | :---: | :---: | :--- |",
        ])
        god_nodes = self.analysis.god_nodes
        if god_nodes:
            for gn in god_nodes[:15]:
                risk = "**CRITICAL**" if gn.total_degree > 30 else ("**HIGH**" if gn.total_degree > 15 else "MEDIUM")
                lines.append(
                    f"| `{gn.node_id}` | `{gn.in_degree}` | `{gn.out_degree}` | `{gn.total_degree}` | {risk} |"
                )
        else:
            lines.append("| *(No excessive God Nodes detected)* | - | - | - | - |")
        lines.append("")

        return "\n".join(lines)

    def _generate_system_metrics_json(self) -> str:
        """Generate 05_system_metrics.json summarizing quantitative metrics."""
        m = self.analysis.metrics
        prof = self.profile

        data = {
            "project_root": self.root_dir,
            "pattern_name": prof.pattern_name if prof else "UNKNOWN",
            "primary_language": prof.primary_language if prof else "UNKNOWN",
            "framework_hints": prof.framework_hints if prof else [],
            "modularity_score_q": round(m.modularity, 4),
            "modularity_verdict": prof.modularity_verdict if prof else "N/A",
            "total_nodes": m.node_count,
            "total_edges": m.edge_count,
            "total_files": m.file_count,
            "total_symbols": m.symbol_count,
            "graph_density": round(m.density, 6),
            "average_degree": round(m.avg_degree, 2),
            "total_communities": m.community_count,
            "total_violations": len(prof.violations) if prof else 0,
            "total_routes": prof.routing_architecture.total_routes if prof and prof.routing_architecture else 0,
            "total_functional_modules": len(prof.functional_modules) if prof else 0,
            # Honest conformance verdict: same dict rendered in 04_dependencies_violations.md.
            "conformance": self._assess_conformance(),
        }
        return json.dumps(data, indent=2)
